// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: microservices-docker
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-03-11
:page-description: Learn how to build a Docker image with Open Liberty.
:page-tags: ['Docker', 'Maven']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kube-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Building a Docker image
:page-seo-description: Find out how to build a Docker image on Open Liberty
:guide-author: Open Liberty
= Building a Docker image

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

You will learn how to write `Dockerfiles`, how to use the `dockerfile-maven-plugin` to create Docker images and how to run instances of the images in Docker containers using `docker run`. 

The application that you will be working with is an `inventory` service,
which stores the information about various JVMs that run on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service communicates with the `system`
service on that host to get these system properties. The system properties are then stored and returned.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]


== Checking out your microservices

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that’s made up of the `system` and `inventory` microservices. Each microservice resides in its own directory, `start/system` and `start/inventory`. 

If you want to learn more about RESTful web services and how to build them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service.
The `inventory` service is built in a similar way.

To try out the application using Maven, first navigate to the `start` directory and then run the following Maven goals to build the application and run it inside Open Liberty:
[role='command']
```
cd start
mvn install liberty:start-server
```

The starting point of the `inventory` service can be found at the http://localhost:9081/inventory/systems[http://localhost:9080/inventory/systems^] URL. It displays the current contents of the inventory.

The `system` service shows the system properties of your local JVM and can be found at the http://localhost:9080/system/properties[^] URL.

The `system` can be added to the `inventory` by visiting the http://localhost:9081/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL.

After you are done checking out the application, stop the Open Liberty server:

[role='command']
```
mvn liberty:stop-server
```
== Building your Docker images

An Docker image is a binary file, made up of multiple layers, used to execute code in a Docker container. Images are built from
instructions, called `Dockerfiles`, to create a complete and executable version of the application.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

Learn how to install Docker on the https://docs.docker.com/engine/installation[official instructions page^].

Learn more about containers on the https://www.docker.com/what-container[official Docker page^].

=== Creating your Dockerfiles

You will be creating two Docker images to run the `inventory` service and `system` service. The first step is to create Dockerfiles for both services.

A Dockerfile is a collection of instructions for building a Docker image that can then be run as a container. Every Dockerfile begins with a parent or base image on top of which various commands are run. For example, you can start your image from scratch and execute commands that download and install Java, or you can start from an image that already contains a Java installation.

[role="code_command hotspot", subs="quotes"]
----
#Create the `inventory/Dockerfile`.#
`inventory/Dockerfile`
----

inventory/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/inventory/Dockerfile[]
----

The [hotspot=1 file=0]`FROM` instruction initializes a new build stage and indicates the parent image from which your
image is built. If you don't need a parent image, then you can use `FROM scratch`, which makes your image a
base image. 

In this case, you're using the `openliberty/open-liberty:javaee8` image as your parent
image, which comes with the latest Open Liberty runtime. There are three different Open Liberty Docker image sets available on Docker Hub and you can learn more about them on the https://github.com/OpenLiberty/ci.docker[OpenLiberty Docker Images repository^].

The `openliberty/open-liberty:javaee8` parent image has a https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/Dockerfile[Dockerfile^] itself. 
The instructions in this `Dockerfile` will be executed along with the rest of the instructions in the `inventory/Dockerfile` that you just created. 

The [hotspot=3-7 file=0]`COPY` instruction copies local files and directories into the destination within your Docker image. It is structured as `COPY <source> <destination>`. 
In this case, the destination is a directory called `/config` which is a symlink created between `opt/ol/wlp/usr/servers/defaultServer` and the `/config` directory. 
This symlink was created in the open-liberty https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/Dockerfile[Dockerfile^].

The [hotspot=3-7 file=0]`COPY` instruction needs to use the user id `1001` and group `0` because that is the user id that is set up in the base image, without this the files and directories copied over would be owned by root.

The `bootstrap.properties`, `server.env` and `server.xml` files contain configuration information such as http ports and features for the application.
Finally, all `.war` files are copied over into `inventory.war`.

The `Dockerfile` for the `system` service follows the same instructions as `inventory` service, except that all the `.war` files are copied over into `system.war`.

[role="code_command hotspot", subs="quotes"]
----
#Create the `system/Dockerfile`.#
`system/Dockerfile`
----

system/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/system/Dockerfile[]
----

=== Using  Maven plugin to build your Docker images

Now that your microservices are complete and you have written your Dockerfiles, you will build your Docker images. 

To build your image, you need to have Docker installed. For installation
instructions, see the https://docs.docker.com/install/[Official Docker Docs^].

You will build your Docker image using the `dockerfile-maven` plug-in. Add this plug-in to your `pom.xml` for your `inventory` and `system` services. 

[role="code_command hotspot", subs="quotes"]
----
#Replace the `inventory/pom.xml`.#
`inventory/pom.xml`
----

The [hotspot=119-122 file=0]`dockerfile-maven` plug-in automatically builds a Docker image from a `Dockerfile` that is located in the same
directory as the [hotspot]`pom.xml` file.

inventory/pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/inventory/pom.xml[]
----

[role="code_command hotspot", subs="quotes"]
----
#Replace the `system/pom.xml`.#
`system/pom.xml`
----

system/pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/system/pom.xml[]
----

=== Creating your Docker image

To build and containerize the application, start your Docker daemon and run the following command:

[role='command']
```
mvn package
```
To verify that the image is built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your two images `inventory` and `system` should appear in the list of all Docker images:
[source, role="no_copy"]
```
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
inventory                                  1.0-SNAPSHOT        08fef024e986        4 minutes ago       471MB
system                                     1.0-SNAPSHOT        1dff6d0b4f31        5 minutes ago       470MB
```


== Running your microservices in Docker containers

Now that you have your two images built, you will run your microservices in Docker containers:
[role='command']
```
docker run -d --name system -p 9080:9080 system:1.0-SNAPSHOT
docker run -d --name inventory -p 9081:9081 inventory:1.0-SNAPSHOT
```

The flags are described in the table below: 

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the container ports to the host ports.
|===

Next, run the `docker ps` command to verify that your containers are started:
[role='command']
```
docker ps
```

Make sure that your container is running and does not have `Exited` as its status:

[source, role="no_copy"]
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                        NAMES
2b584282e0f5        inventory:1.0-SNAPSHOT   "/opt/ol/helpers/run…"   2 seconds ago       Up 1 second         9080/tcp, 9443/tcp, 0.0.0.0:9081->9081/tcp   inventory
99a98313705f        system:1.0-SNAPSHOT      "/opt/ol/helpers/run…"   3 seconds ago       Up 2 seconds        0.0.0.0:9080->9080/tcp, 9443/tcp             system
```

To access the application, point your browser to the http://localhost:9081/inventory/systems[http://localhost:9080/inventory/systems^] URL. As you might expect, these are empty since
nothing is stored in the inventory yet. 

Point your browser to the http://localhost:9080/system/properties[^] URL. This is the `system` service which shows the system properties of your local JVM.

Next, you will to retrieve the `system` containers IP address. When you start Docker,  a default bridge network is created for running containers to be able to communicate. 
Run the following command to retrieve the `system` IP address:
[role='command']
```
docker network inspect bridge
```

You will find the address corresponding to IPv4Address:

```
            "99a98313705fc9f8c21b8110900b8bee0427412373f8c3ef2d733c96d96ffb5f": {
                "Name": "system",
                "EndpointID": "e30b640eb214435c9bf08b23d7c3f851c88e909e4feffd1a893f14ae4d2f35a4",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
```

In this case, the address for `system` is 172.17.0.2, note the IP address for system in order to add the system properties to the inventory service. 

Point your browser to the http://localhost:9081/inventory/systems/system-ip-address[http://localhost:9080/inventory/systems/system-ip-address^] URL by replacing the `system-ip-address` with the value you obtained.
You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory. Go back to http://localhost:9081/inventory/systems[http://localhost:9080/inventory/systems^] and
you see a new entry for `localhost`. For simplicity, only the OS name and username are shown here for
each host. You can repeat this process for your own hostname or any other machine that is running
the `system` service.


== Testing the application

You can test your application manually, but automated tests ensure code quality because they trigger a failure whenever a code change introduces a defect.

[role="code_command hotspot", subs="quotes"]
----
#Create the `SystemEndpointTest` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java`
----

SystemEndpointTest.java
[source, java, linenums, indent=0, role="code_column"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java[tags=!copyright]
----

The [hotspot=52-61 file=0]`testGetProperties()` method checks for a `200` response status from the `system` service endpoint.

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryEndpointTest` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
----

InventoryEndpointTest.java
[source, java, linenums, indent=0, role="code_column"]
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java[tags=!copyright]
----

The [hotspot=69-81 file=1]`testEmptyInventory()` method checks that the `inventory` service has a total of 0 systems before anything is added to it.
The [hotspot=83-103 file=1]`testHostRegistration()` method checks that the `system` service was added to `inventory` properly and `testSystemPropertiesMatch()` checks that the `system` properties match what was added into the `inventory`.
Finally, [hotspot=133-149 file=1]`testUnknownHost()` checks that an error is raised if an unknown host name is being added into the `inventory` service.

The [hotspot=35 file=1]`systemServiceIp` is the same value that you retrieved in the previous section to manually add the `system` service into the `inventory`. 
This value will also be passed in when you run the tests. 

=== Running the tests

Verify that the tests pass using the Maven `verify` goal:
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dsystem.ip=[system-ip-address]
```

If the tests pass, you will see a similar output to the following:
[source, role="no_copy"]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

To stop your container, run the following command from the command line.
[role='command']
```
docker stop rest-app
```

If a problem occurs and your container exits prematurely, the container won't appear in the container
list that the `docker ps` command displays. Instead, your container appears with an `Exited`
status when you run the `docker ps -a` command. Run the `docker logs rest-app` command to view the
container logs for any potential problems and double-check that your Dockerfile is correct. When you
find the cause of the issue, remove the faulty container with the `docker rm rest-app` command, rebuild
your image, and start the container again.

== Great work! You're done!

You have just completed building a Docker image with two microservices in Open Liberty. 

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]
