// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: microservices-docker
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-03-11
:page-description: Learn how to containerize microservices with Open Liberty.
:page-tags: ['Docker', 'Maven']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Containerizing microservices
:page-seo-description: Find out how to containerize microservices on Open Liberty
:guide-author: Open Liberty
= Containerizing microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to containerize your micoservices with Open Liberty by Docker and run them in isolated containers.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

To accelerate your development, you may use the containerization technology to deploy and run your microservices into isolated containers instead of 
different physical or virtual machines. 

Application containerization is to bundle an application with its entire environment, meaning all of its
required libraries, dependencies, and configuration files, so that it can run in any containerization  ecosystem, 
such as Docker, and it can also be deployed to Kubernetes.

You'll learn how to construct a `Dockerfile`, how to create a Docker image by using `docker build`  command, and how to run the image in Docker container 
by using `docker run` command.

The two  microservices that you'll be working with are called `system` and `inventory`. The `system` microservice returns the JVM system properties 
of the running container.  The `inventory` microservice adds the properties from the `system` microservice to the inventory. This guide demonstrates how both microservices can be run and communicate
in different isolated containers. 

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]


== Packaging your microservices

Navigate to the `start` directory to begin.
The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that’s made up of the `system` and `inventory` microservices. Each microservice resides in its own directory, `system` and `inventory`, respectively. 

If you want to learn more about RESTful web services and how to build them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service.
The `inventory` service is built in a similar way.

To try out the application using Maven, run the following Maven goals to build the application and run it inside Open Liberty:
[role='command']
```
mvn install 
mvn liberty:start-server
```

The [hotspot=packageFile]`<packageFile>` tag in the [hotspot]`pom.xml` configures the microservices to be packaged in an archive form.
The `system` and `inventory` microservices including the application `WAR` and server configuration files are archived into `system/target/system.tar.gz` and `inventory/target/inventory.tar.gz`.

To access the `inventory` service, which displays the current contents of the inventory, visit the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL.

The `system` service shows the system properties of your local JVM and can be found at the http://localhost:9080/system/properties[^] URL.

The system properties of your localhost can be added to the `inventory` by visiting the http://localhost:9081/inventory/systems/localhost[http://localhost:9081/inventory/systems/localhost^] URL.

After you are done checking out the application, stop the Open Liberty server:

[role='command']
```
mvn liberty:stop-server
```
pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/pom.xml[]
----
== Building your Docker images

A Docker image is a binary file, made up of multiple layers, and used to execute code in a Docker container. Images are built from
instructions, defined in `Dockerfiles`, to create a containerized version of the application.

A Dockerfile is a collection of instructions for building a Docker image that can then be run as a container. Every Dockerfile begins with a parent or base image on top of which various commands are run. For example, you can start your image from scratch and execute commands that download and install Java, or you can start from an image that already contains a Java installation.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

Install Docker by following the instructions on the https://docs.docker.com/engine/installation[official page^].

=== Creating your Dockerfiles

You will be creating two Docker images to run the `inventory` service and `system` service. The first step is to create Dockerfiles for both services.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `Dockerfile` for the inventory service.#
`inventory/Dockerfile`
----

inventory/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/inventory/Dockerfile[]
----

The [hotspot=from file=0]`FROM` instruction initializes a new build stage, which indicates the parent image of the
image that  has been built. If you don't need a parent image, then you can use `FROM scratch`, which makes your image a
base image. 

In this case, you're using the `open-liberty` image as your parent
image, which comes with the latest Open Liberty runtime by default. You can find all different official images at the https://hub.docker.com/_/open-liberty[open-liberty DockerHub^]. To pull different open-liberty image, like `kernel`, you may define the `FROM` instruction as `FROM open-liberty:kernel`.

The [hotspot=add file=0]`ADD` instruction is structured as [hotspot=add file=0]`ADD` [hotspot=5 file=0]`[--chown=<user>:<group>]` [hotspot=6 file=0]`<source>` [hotspot=7 file=0]`<destination>`. 
It copies local files and directories into the destination within your Docker image. If the source  is an archive, the [hotspot=add file=0]`ADD` instruction will unpack it into the destination directory.
In this case, the inventory archived application file [hotspot=6 file=0]`inventory.tar.gz`, that was created from running `mvn install`, will be extracted to the destination directory [hotspot=7 file=0]`/opt/ol`. 

The [hotspot=add file=0]`ADD` instruction needs to use the user id [hotspot=5 file=0]`1001` and group [hotspot=5 file=0]`0` because the `OpenLiberty` image runs by default with the `USER 1001` (non-root) for security purposes. Without this, the files and directories copied over would be owned by root.

The `Dockerfile` for the `system` service follows the same instructions as `inventory` service, except that the [hotspot=add file=1]`system.tar.gz` files are copied over into `/opt/ol`.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `Dockerfile` for the system service.#
`system/Dockerfile`
----

system/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/system/Dockerfile[]
----

=== Building your Docker image

Now that your microservices are packaged and you have written your Dockerfiles, you will build your Docker images using the `docker build` command. To build your image, you need to have Docker installed and your Docker daemon started.

Run the following commands to build container images for your application:

[role='command']
```
docker build -t system system/.
docker build -t inventory inventory/.
```

The `-t` flag in the `Docker build` command allows the docker image to be in `name[:tag]` format. 
The tag for an image describes the specific image version. If the `[:tag]` is not specified, the `latest` version will be created by default.
To verify that the images are built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your two images `inventory` and `system` should appear in the list of all Docker images:
[role="no_copy"]
----
REPOSITORY    TAG       IMAGE ID        CREATED          SIZE
inventory     latest    08fef024e986    4 minutes ago    471MB
system        latest    1dff6d0b4f31    5 minutes ago    470MB
----


== Running your microservices in Docker containers

Now that you have your two images built, you will run your microservices in Docker containers:
[role='command']
```
docker run -d --name system -p 9080:9080 system
docker run -d --name inventory -p 9081:9080 inventory
```

The flags are described in the table below: 

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the host ports to the container ports. For example: `-p <HOST_PORT>:<CONTAINER_PORT>`
|===

Next, run the `docker ps` command to verify that your containers are started:
[role='command']
```
docker ps
```

Make sure that your containers are running and shows `Up` as their status:

[role="no_copy"]
----
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS           PORTS                                        NAMES
2b584282e0f5   inventory:latest   "/opt/ol/helpers/run…"   2 seconds ago    Up 1 second      9080/tcp, 9443/tcp, 0.0.0.0:9081->9081/tcp   inventory
99a98313705f   system:latest      "/opt/ol/helpers/run…"   3 seconds ago    Up 2 seconds     0.0.0.0:9080->9080/tcp, 9443/tcp             system
----

If a problem occurs and your containers exit prematurely, the containers won't appear in the container
list that the `docker ps` command displays. Instead, your containers appear with an `Exited`
status when running the `docker ps -a` command. Run the `docker logs system` and `docker logs inventory` commands to view the
container logs for any potential problems. You can also double-check that your Dockerfiles are correct. When you
find the cause of the issues, remove the faulty containers with the `docker rm system` and `docker rm inventory` commands, rebuild
your images, and start the containers again.

To access the application, point your browser to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL. 
An empty list is expected because no system properties are stored in the inventory yet. 

Next, you will retrieve the `system` container's IP address by using the `system` container name we defined when running the docker containers. 
Run the following command to retrieve the `system` IP address:
[role='command']
```
docker inspect -f "{{.NetworkSettings.IPAddress }}" system
```

You will find the `system` container's IP address:
[role="no_copy"]
----
172.17.0.2
----


In this case, the address for `system` is `172.17.0.2`. Take note of the address `[system-ip-address]` in order to add the system properties to the inventory service. 

Point your browser to the `\http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` URL by replacing the `[system-ip-address]` with the value you obtained.
You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory. Go back to http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] and
you see a new entry for `[system-ip-address]`. 

== Testing the microservices

You can test your microservices manually by hitting the endpoints or with automated tests that check the microservices locally and against the docker containers.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointTest` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java`
----

SystemEndpointTest.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java[]
----

The [hotspot=testGetProperties file=0]`testGetProperties()` method checks for a `200` response status from the `system` service endpoint.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryEndpointTest` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
----

InventoryEndpointTest.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java[]
----

* The [hotspot=testEmptyInventory file=1]`testEmptyInventory()` method checks that the `inventory` service has a total of 0 systems before anything is added to it.
* The [hotspot=testHostRegistration file=1]`testHostRegistration()` method checks that the `system` service was added to `inventory` properly.
* The [hotspot=testSystemPropertiesMatch file=1]`testSystemPropertiesMatch()` checks that the `system` properties match what was added into the `inventory`.
* The [hotspot=testUnknownHost file=1]`testUnknownHost()` checks that an error is raised if an unknown host name is being added into the `inventory` service.
* The [hotspot=systemServiceIp file=1]`systemServiceIp` is the same value that you retrieved in the previous section to manually add the `system` service into the `inventory` service. This value will also be passed in when you run the tests. 

=== Running the tests

Run the Maven `verify` goal to test the services running in the docker containers by replacing the `[system-ip-address]` with the value determined in the previous section.
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dsystem.ip=[system-ip-address]
```

If the tests pass, you will see a similar output as the following:
[role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.653 s - in it.io.openliberty.guides.system.SystemEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

When you are finished with the services, run the following commands to stop and remove your containers.
[role='command']
```
docker stop inventory system 
docker rm inventory system
```

== Great work! You're done!

You have just built Docker images for two microservices in Open Liberty. 

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]
