// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: microservices-docker
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-03-11
:page-description: Learn how to containerize microservices with Open Liberty.
:page-tags: ['Docker', 'Maven']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Containerizing microservices
:page-seo-description: Find out how to containerize microservices on Open Liberty
:guide-author: Open Liberty
= Containerizing microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to build a docker image.

== What you'll learn

You will learn how to write `Dockerfiles`, how to use the `docker build` to create Docker images and how to run instances of the images in Docker containers using `docker run`. 
Application containerization is to bundle an application with its entire environment, meaning all of its required libraries, dependencies, and configuration files.
The container can be ran on any machine that is running running Docker regardless of how that machine's environment is set up.
You can also run multiple containers on a single machine in isolation from one another so that two containers that have different
versions of a certain technology do not interfere with each other.

The application that you will be working with is an `inventory` service,
which stores the information about various JVMs that run on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service communicates with the `system`
service on that host to get these system properties. The system properties are then stored and returned.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]


== Packaging your microservices

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that’s made up of the `system` and `inventory` microservices. Each microservice resides in its own directory, `start/system` and `start/inventory`, respectively. 

If you want to learn more about RESTful web services and how to build them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service.
The `inventory` service is built in a similar way.

To try out the application using Maven, first, navigate to the `start` directory and then run the following Maven goals to build the application and run it inside Open Liberty:
[role='command']
```
mvn install 
mvn liberty:start-server
```

In the `pom.xml`, the application has been specified to be packaged in an archive form with the [hotspot=packageFile]`<package.file>` tag.
The `system` and `inventory` microservices including the application `WAR` and server configuration files are archived into `system/target/system.tar.gz` and `inventory/target/inventory.tar.gz`.

The starting point of the `inventory` service can be found at the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL. It displays the current contents of the inventory.

The `system` service shows the system properties of your local JVM and can be found at the http://localhost:9080/system/properties[^] URL.

The system properties of your localhost can be added to the `inventory` by visiting the http://localhost:9081/inventory/systems/localhost[http://localhost:9081/inventory/systems/localhost^] URL.

After you are done checking out the application, stop the Open Liberty server:

[role='command']
```
mvn liberty:stop-server
```
pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/pom.xml[]
----
== Building your Docker images

A Docker image is a binary file, made up of multiple layers, used to execute code in a Docker container. Images are built from
instructions, called `Dockerfiles`, to create a containerized version of the application.

A Dockerfile is a collection of instructions for building a Docker image that can then be run as a container. Every Dockerfile begins with a parent or base image on top of which various commands are run. For example, you can start your image from scratch and execute commands that download and install Java, or you can start from an image that already contains a Java installation.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

Install Docker on the https://docs.docker.com/engine/installation[official instructions page^].

=== Creating your Dockerfiles

You will be creating two Docker images to run the `inventory` service and `system` service. The first step is to create Dockerfiles for both services.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `inventory/Dockerfile`.#
`inventory/Dockerfile`
----

inventory/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/inventory/Dockerfile[]
----

The [hotspot=from file=0]`FROM` instruction initializes a new build stage, which indicates the parent image of the
image that  has been built. If you don't need a parent image, then you can use `FROM scratch`, which makes your image a
base image. 

In this case, you're using the `open-liberty` image as your parent
image, which comes with the latest Open Liberty runtime by default. You can find all different official images at the https://hub.docker.com/_/open-liberty[open-liberty DockerHub^]. To pull different open-liberty image, like `kernel`, you may define the `FROM` instructions as `FROM open-liberty:kernel`.

There are three different Open Liberty Docker image sets available on Docker Hub. You can learn more about them on the https://github.com/OpenLiberty/ci.docker[OpenLiberty Docker Images repository^].

The [hotspot=add file=0]`ADD` instruction is structured as [hotspot=add file=0]`ADD` [hotspot=6 file=0]`<source>` [hotspot=7 file=0]`<destination>`. 
It copies local files and directories into the destination within your Docker image. If the source  is an archive, the [hotspot=add file=0]`ADD` instruction will unpack it into the destination directory.
In this case, the inventory archived application file [hotspot=6 file=0]`inventory.tar.gz`, that was created frmo running `mvn install`, will be extracted to the destination directory [hotspot=7 file=0]`opt/ol`. 

The [hotspot=add file=0]`ADD` instruction needs to use the user id [hotspot=5 file=0]`1001` and group [hotspot=5 file=0]`0` because the `OpenLiberty` image runs by default with the `USER 1001` (non-root). Without this, the files and directories copied over would be owned by root.
The `Dockerfile` for the `system` service follows the same instructions as `inventory` service, except that the [hotspot=add file=1]`system.tar.gz` files are copied over into `/opt/ol`.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `system/Dockerfile`.#
`system/Dockerfile`
----

system/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/system/Dockerfile[]
----

=== Creating your Docker image

Now that your microservices are complete and you have written your Dockerfiles, you will build your Docker images using the `docker build` command.

To build your image, you need Docker to have Docker installed and your Docker daemon started.

You will build your Docker image using the `docker build` command. To build and containerize the application, run the following commands:

[role='command']
```
docker build -t system system/.
docker build -t inventory inventory/.
```

The `-t` flag in the `docker build` command allows the docker images to be in `name[:tag]` format. 
The tag for an image describes the specific image version because [:tag] is not specified, the `latest` version will be created by default.
To verify that the images are built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your two images `inventory` and `system` should appear in the list of all Docker images:
[role="no_copy"]
----
REPOSITORY   TAG           IMAGE ID            CREATED             SIZE
inventory    latest        08fef024e986        4 minutes ago       471MB
system       latest        1dff6d0b4f31        5 minutes ago       470MB
----


== Running your microservices in Docker containers

Now that you have your two images built, you will run your microservices in Docker containers:
[role='command']
```
docker run -d --name system -p 9080:9080 system
docker run -d --name inventory -p 9081:9081 inventory
```

The flags are described in the table below: 

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the container ports to the host ports.
|===

Next, run the `docker ps` command to verify that your containers are started:
[role='command']
```
docker ps
```

Make sure that your containers are running and shows `Up x seconds` as their status:

[role="no_copy"]
----
CONTAINER ID   IMAGE            COMMAND                  CREATED          STATUS           PORTS                                        NAMES
2b584282e0f5   inventory:latest "/opt/ol/helpers/run…"   2 seconds ago    Up 1 second      9080/tcp, 9443/tcp, 0.0.0.0:9081->9081/tcp   inventory
99a98313705f   system:latest    "/opt/ol/helpers/run…"   3 seconds ago    Up 2 seconds     0.0.0.0:9080->9080/tcp, 9443/tcp             system
----

To access the application, point your browser to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL. 
An empty list is expected because no system properties are stored in the inventory yet. 

Point your browser to the http://localhost:9080/system/properties[^] URL. The `system` service shows the system properties of the `system` container JVM.

Next, you will retrieve the `system` containers IP address. When you start Docker,  a default bridge network is created for running containers to be able to communicate. 
Run the following command to retrieve the `system` IP address:
[role='command']
```
docker network inspect bridge
```

You will find the address corresponding to IPv4Address:

```
"99a98313705fc9f8c21b8110900b8bee0427412373f8c3ef2d733c96d96ffb5f": {
    "Name": "system",
    "EndpointID": "e30b640eb214435c9bf08b23d7c3f851c88e909e4feffd1a893f14ae4d2f35a4",
    "MacAddress": "02:42:ac:11:00:02",
    "IPv4Address": "172.17.0.2/16",
    "IPv6Address": ""
}
```

In this case, the address for `system` is `172.17.0.2`. Note down the `[system-ip-address]` in order to add the system properties to the inventory service. 

Point your browser to the `\http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` URL by replacing the `[system-ip-address]` with the value you obtained.
You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory. Go back to http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] and
you see a new entry for `[system-ip-address]`. As you can see, the `os.name` is `Linux` because the base image was pulled from a `Linux` image.

If a problem occurs and your containers exit prematurely, the containers won't appear in the container
list that the `docker ps` command displays. Instead, your containers appear with an `Exited`
status when running the `docker ps -a` command. Run the `docker logs system` and `docker logs inventory` commands to view the
container logs for any potential problems. You can also double-check that your Dockerfiles are correct. When you
find the cause of the issues, remove the faulty containers with the `docker rm system` and `docker rm inventory` commands, rebuild
your images, and start the containers again.

== Testing the microservices

You can test your microservices manually or with automated tests that test the microservices running locally and against the docker container.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointTest` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java`
----

SystemEndpointTest.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java[]
----

The [hotspot=testGetProperties file=0]`testGetProperties()` method checks for a `200` response status from the `system` service endpoint.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryEndpointTest` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java`
----

InventoryEndpointTest.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java[]
----

* The [hotspot=testEmptyInventory file=1]`testEmptyInventory()` method checks that the `inventory` service has a total of 0 systems before anything is added to it.
* The [hotspot=testHostRegistration file=1]`testHostRegistration()` method checks that the `system` service was added to `inventory` properly.
* The [hotspot=testSystemPropertiesMatch file=1]`testSystemPropertiesMatch()` checks that the `system` properties match what was added into the `inventory`.
* The [hotspot=testUnknownHost file=1]`testUnknownHost()` checks that an error is raised if an unknown host name is being added into the `inventory` service.
* The [hotspot=systemServiceIp file=1]`systemServiceIp` is the same value that you retrieved in the previous section to manually add the `system` service into the `inventory` service. This value will also be passed in when you run the tests. 

=== Running the tests

Run the Maven `verify` goal to test the services running in the docker containers by replacing the `[system-ip-address]` with the value determined in the previous section.
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dsystem.ip=[system-ip-address]
```

If the tests pass, you will see a similar output as the following:
[role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.653 s - in it.io.openliberty.guides.system.SystemEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

When you are finished with the services, run the following commands to stop your containers.
[role='command']
```
docker stop inventory system 
docker rm inventory system
```

== Great work! You're done!

You have just built Docker images for two microservices in Open Liberty. 

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]
