// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: microservices-docker
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-03-11
:page-description: Learn how to build a Docker image with Open Liberty.
:page-tags: ['Docker', 'Maven']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kube-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Building a Docker image
:page-seo-description: Find out how to build a Docker image on Open Liberty
:guide-author: Open Liberty
= Building a Docker image

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

== What you'll learn

You will learn how to create two Docker images from the Open Liberty image with two microservices on them using `Dockerfiles` and the `dockerfile-maven-plugin`.
Then you will then run instances of those two images in two Docker containers using `docker run`.

=== What is Docker?

Docker is a tool that you can use to deploy and run applications with containers. You
can think of Docker like a virtual machine that runs various applications. However, unlike a typical virtual
machine, you can run these applications simultaneously on a single system and independent of
one another.

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

Learn how to install Docker on the https://docs.docker.com/engine/installation[official instructions page^].

=== What is a container?

A container is a lightweight, stand-alone package that contains a piece of software that is bundled together
with the entire environment that it needs to run. Containers are small compared to regular images and can
run on any environment where Docker is set up. Moreover, you can run multiple containers on a single
machine at the same time in isolation from each other.

Learn more about containers on the https://www.docker.com/what-container[official Docker page^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc[]


== Creating your microservices?

* Creating System service 
* Creating Inventory service 
* Emphasize how the two services communicate 
* Re-use the following if we are not going to ask users to create the microservices: 

The starting Java project, which you can find in the start directory, is a multi-module Maven project that’s made up of the system and inventory microservices. Each microservice resides in its own directory, start/system and start/inventory. 


== Creating your Dockerfiles

A Dockerfile is a collection of instructions for building a Docker image that can then be run as a container. Every Dockerfile begins with a parent or base image on top of which various commands are run. For example, you can start your image from scratch and execute commands that download and install Java, or you can start from an image that already contains a Java installation.

=== Dockerfiles for inventory and system services

[role="code_command hotspot", subs="quotes"]
----
#Create the `inventory/Dockerfile`.#
`inventory/Dockerfile`
----

inventory/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/inventory/Dockerfile[]
----

The [hotspot=1 file=0]`FROM` instruction initializes a new build stage and indicates the parent image from which your
image is built. If you don't need a parent image, then you can use `FROM scratch`, which makes your image a
base image. 

In this case, you're using the `openliberty/open-liberty:javaee8`[https://github.com/OpenLiberty/ci.docker^] image as your parent
image, which comes with the latest Open Liberty runtime.

The `openliberty/open-liberty:javaee8` parent image has a `Dockerfile`[https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/Dockerfile^] itself. 
The commands in this `Dockerfile` will be executed along with the rest of the commands in the `inventory/Dockerfile` that you just created. 

The `COPY` instruction copies local files and directories into the destination within your Docker image. It is structured as `COPY <source> <destination>`. 
In this case, the destination is a directory called `/config` which is a symlink created between `opt/ol/wlp/usr/servers/defaultServer` and the `/config` directory. 
This symlink was created in the open-liberty `Dockerfile`[https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/Dockerfile^].

The `COPY` instruction needs to use the user id `1001` and group `0` because that is the user id that is set up in the base image, without this the files and directories copied over would be owned by root.

The `bootstrap.properties`, `server.env` and `server.xml` files contain configuration information such as http ports and features for the application.
Finally, all `.war` files are copied over into `inventory.war`.

The `Dockerfile` for the `system` service follows the same instructions as `inventory` service, except that all the `.war` files are copied over into `system.war`.

[role="code_command hotspot", subs="quotes"]
----
#Create the `system/Dockerfile`.#
`system/Dockerfile`
----

system/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/system/Dockerfile[]
----

== Build your Docker images

Now that your microservices are complete and you have written your Dockerfiles, you will build your Docker images. 

To build your image, you need to have Docker installed. For installation
instructions, see the https://docs.docker.com/install/[Official Docker Docs^].

The `dockerfile-maven` plug-in automatically builds a Docker image from a `Dockerfile` that is located in the same
directory as the [hotspot]`pom.xml` file.

inventory/pom.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/inventory/pom.xml[]
----

To build and containerize the application, start your Docker daemon and run the following command:

[role='command']
```
mvn package
```


== Testing the application

SystemEndpointTest.java
[source, java, linenums, indent=0, role="code_column"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java[]
----
//--** Show how to test your application.


//--** Include this for info on how to run the tests


//--** Including a listing block with test results here
//--** Show console output of the test results

//--** OPTIONAL: after listing the test results, mention a simple change a user can make/introduce that
//--** will cause the tests to fail. Be brief and don't give the users all of the instructions.
//--** At this point, they should be comfortable enough to figure it out on their own.




== Great work! You're done!

//--** Briefly summarize what the user achieved in this guide (1-2 sentences).
EXAMPLE: You have just completed building a simple todo list application using JAXRS and CDI services in Open Liberty.

//--** OPTIONAL: briefly state what the user could do next now that they've learned the
//--** technologies in this guide.

//--** Include the below from the guides-common repo to tell users how they can contribute to the guide
include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]
