# tag::from[]
FROM open-liberty
# end::from[]
# tag::add[]
# tag::userID[]
ADD --chown=1001:0 \
# end::userID[]
    # tag::source[]
    target/inventory.tar.gz \
    # end::source[]
    # tag::destination[]
    /opt/ol
    # end::destination[]
# end::add[]
